src/app/material/models.py
from datetime import datetime
from app import db, whooshee
from app.models import BaseModelMixin
from app.classroom.models import MaterialGroup
from app.auth.enums import Role
from .enums import StatusEnum


@whooshee.register_model('title', 'article')
class Material(BaseModelMixin, db.Model):
    __searchable__ = ['title', 'article']
    title = db.Column(db.String(250), nullable=False, default='')
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    author = db.relationship('User', foreign_keys=author_id)
    status = db.Column(db.Integer, default=StatusEnum.DRAFT.value, nullable=False)
    article = db.Column(db.String, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    commets = db.relationship('Comment', lazy='dynamic', cascade='all, delete-orphan')
    groups = db.relationship('MaterialGroup', lazy='dynamic', cascade='all, delete-orphan')

    @property
    def status_label(self):
        return StatusEnum.label(self.status)

    def update_groups(self, groups):
        self.groups.delete()
        self.groups.extend(MaterialGroup(
            material_id=self.id, classroom_id=group.id) for group in groups)


class Comment(BaseModelMixin, db.Model):
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    author = db.relationship('User', foreign_keys=author_id)
    published = db.Column(db.DateTime, nullable=False, default=datetime.now)
    material_id = db.Column(db.Integer, db.ForeignKey('material.id'), nullable=False)
    material = db.relationship('Material', foreign_keys=material_id)
    message = db.Column(db.String(250), nullable=False, server_default='')

    def allow_edit(self, user):
        return self.author_id == user.id or user.has_role(Role.ADMIN)

src/app/material/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, SelectField, TextAreaField, SubmitField, DateTimeField)
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField
from wtforms.validators import DataRequired, Length

from app.classroom.models import Classroom
from .enums import StatusEnum


class MaterialCreateForm(FlaskForm):
    title = StringField('Название', validators=[DataRequired(), Length(max=250)])
    status = SelectField('Статус', coerce=int, choices=StatusEnum.choices(), validators=[DataRequired()])
    published = DateTimeField('Дата публикации', format='%d.%m.%Y %H:%M', validators=[DataRequired()])
    article = TextAreaField(validators=[DataRequired()])
    groups = QuerySelectMultipleField('Группы', allow_blank=False, 
        query_factory=lambda: Classroom.query.all())
    submit = SubmitField('Сохранить')


class CommentForm(FlaskForm):
    message = TextAreaField('Комментарий:', validators=[DataRequired(), Length(max=250)])
    submit = SubmitField('Отправить')

src/app/material/views.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_user import current_user, confirm_email_required
from flask_login import login_required

from app import db
from app.auth.decorators import cake
from app.auth.enums import Role
from app.classroom.models import MaterialGroup, Classroom

from .models import Material, Comment
from .forms import MaterialCreateForm, CommentForm
from .enums import StatusEnum


mod_material = Blueprint('material', __name__, url_prefix='/material',
                         template_folder='templates')


@mod_material.route('/', methods=['GET', 'POST'])
@mod_material.route('/<int:page>', methods=['GET', 'POST'])
@login_required
@confirm_email_required
def list_view(page=1):

    query = Material.query
    q = request.args.get('q')
    if q:
        query = query.whooshee_search(q)

    if current_user.role == Role.STUDENT:
        query = query.outerjoin(MaterialGroup).filter(
            (MaterialGroup.classroom_id==current_user.classroom_id) |
            (MaterialGroup.classroom_id==None)
        )

    query = query.filter(
        (Material.author_id == current_user.id) |
        ((Material.status == StatusEnum.PUBLISHED.value) &
         (Material.published <= datetime.now()))
    ).order_by(Material.published.desc()).distinct()

    materials = query.paginate(page, 5, True)

    return render_template('material/list.html', materials=materials)


@mod_material.route('/add', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def create_view():
    form = MaterialCreateForm()
    if form.validate_on_submit():
        material = Material(
            title=form.title.data,
            status=form.status.data,
            published=form.published.data,
            article=form.article.data,
            author_id=current_user.id
        )
        db.session.add(material)
        material.update_groups(form.groups.data)
        db.session.commit()
        return redirect(url_for('material.list_view'))
    return render_template('material/create.html', form=form)


@mod_material.route('/delete/<int:id>')
@cake(Role.TEACHER)
def delete_view(id):
    material = Material.query.get_or_404(id)
    if current_user.id == material.author_id:
        db.session.delete(material)
        db.session.commit()
    return redirect(url_for('material.list_view'))



@mod_material.route('/edit/<int:id>', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def edit_view(id):
    material = Material.query.get_or_404(id)
    if current_user.id != material.author_id:
        return redirect(url_for('material.list_view'))
    form = MaterialCreateForm(obj=material)
    if form.validate_on_submit():
        material.title = form.title.data
        material.status = form.status.data
        material.published = form.published.data
        material.article = form.article.data
        material.update_groups(form.groups.data)
        db.session.commit()
        return redirect(url_for('material.list_view'))
    form.groups.data = material.groups.join(Classroom).with_entities(Classroom)
    return render_template('material/create.html', form=form, material=material)


@mod_material.route('/view/<int:id>', methods=['GET'])
@login_required
@confirm_email_required
def item_view(id):
    material = Material.query.get_or_404(id)
    comments = Comment.query.filter_by(material_id=id)
    comment_form = CommentForm()
    return render_template('material/view.html', material=material,
                           comments=comments, comment_form=comment_form)


@mod_material.route('/comments/add/<int:material_id>', methods=['POST'])
@login_required
@confirm_email_required
def comment_add(material_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            author_id=current_user.id,
            material_id=material_id,
            message=form.message.data
        )
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('material.item_view', id=material_id))


@mod_material.route('/comments/delete/<int:id>')
@login_required
@confirm_email_required
def comment_delete(id):
    comment = Comment.query.get_or_404(id)
    material_id = comment.material_id
    if comment.allow_edit(current_user):
        db.session.delete(comment)
        db.session.commit()
    return redirect(url_for('material.item_view', id=material_id))


@mod_material.route('/comments/edit/', methods=['POST'])
@login_required
@confirm_email_required
def edit_comment():
    comment_id = request.form.get('id')
    new_value = request.form.get('value')
    if comment_id and new_value:
        id = int(comment_id.replace('comment_', ''))
        comment = Comment.query.get_or_404(id)
        if comment.allow_edit(current_user):
            comment.message = new_value[:250]
            db.session.commit()
        return new_value
    return redirect(url_for('material.list_view'))

src/app/templates/material/create.html
{% extends 'base.html' %}


{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}

<div class="container">

        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <form action="" method="POST" role="form">
                    {{ form.hidden_tag() }}
                    {{ render_field(form.title, tabindex=230) }}
                    {{ render_field(form.status, tabindex=230) }}
                    {{ render_field(form.published, tabindex=230) }}
                    {{ render_field(form.groups, tabindex=230, **{'data-placeholder': " "}) }}
                    {{ render_field(form.article, tabindex=230, **{'data-provide': "markdown"}) }}
                    <div>
                        {{ render_submit_field(form.submit, tabindex=280) }}
                        {% if material %}
                            <div class="pull-right delete_button">
                                <a href="{{ url_for('material.delete_view', id=material.id) }}" class="btn btn-danger btn-md" role="button">Удалить</a>
                            </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $( document ).ready(function() {
            $('#published').datetimepicker({
                format:'d.m.Y H:i'
            });
        });
        $('#groups').chosen();
    </script>
{% endblock %}

src/app/templates/material/list.html
{% extends 'base.html' %}


{% block content %}
<div class="container">

        <div class="row">
            <div class="col-lg-8">
                {% for material in materials.items %}
                    <div class="col-lg-12">
                            <h1>
                            {% if current_user.id == material.author_id and current_user.role == Role.TEACHER %}
                            <a href="{{ url_for('material.edit_view', id=material.id) }}">
                                {{ material.title }}
                            </a>
                            {% else %}
                                {{ material.title }}
                            {% endif %}
                            </h1>

                        <p>
                            {{ material.article|truncate(400)}}
                            <a href="{{ url_for('material.item_view', id=material.id) }}">
                                Читать
                            </a>
                        </p>
                        <span class="badge">{{ material.status_label }} {{ material.published|datetimeformat }}</span>
                        <div class="pull-right">{{ material.author.first_and_last_name }}</div>
                    <hr>
                    </div>
                {% else %}
                    <div class="col-lg-12">
                        <h2>Ничего нет</h2>
                    </div>
                {% endfor %}
            </div>

            <div class="col-md-4">
                <div class="well">
                    <h4>Поиск</h4>
                    <div class="input-group">
                        <form action="" method="get" class="form-inline form-style-disabled">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q">
                            </div>
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </form>
                    </div>
                    <!-- /.input-group -->
                </div>
                {% if current_user.role == Role.TEACHER %}
                    <div>
                        <a href="{{ url_for('material.create_view') }}" class="btn btn-info btn-md" role="button">Отправить статью</a>
                    </div>
                {% endif %}

            </div>

        </div>
        {% if materials.has_prev %}
        <a href="{{ url_for('material.list_view', page=materials.prev_num) }}"><< Предыдущая</a>
        {% else %}<< Предыдущая
        {% endif %} | 
        {% if materials.has_next %}
        <a href="{{ url_for('material.list_view', page=materials.next_num) }}">Следующая >></a>
        {% else %}Следующая >>
        {% endif %}
{% endblock %}

src/app/templates/material/view.html
{% extends 'base.html' %}


{% block head %}
    <style type="text/css">
        .destroy {
            border: none;
        }
        .media-body:hover .delete_button{
            visibility: visible;
        }
        .delete_button{
            visibility: hidden;
        }
    </style>
{% endblock %}



{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<div class="container">

    <span class="badge">{{ material.status_label }} {{ material.published|datetimeformat }}</span>
    <div class="pull-right">{{ material.author.first_and_last_name }}</div>
    <hr>
    <h2>{{ material.title }}</h2> 
    <p>
        {{ material.article|markdown }}
    </p>
    <div class="well">
        <form class="form-style-disabled" action="{{ url_for('material.comment_add', material_id=material.id) }}" method="POST" role="form">
            {{ comment_form.hidden_tag() }}
            {{ render_field(comment_form.message) }}
            {{ render_submit_field(comment_form.submit) }}
        </form>
    </div>
    <div id="comments">
        {% for comment in comments %}
            <hr>
            <div class="media comment">
                <div class="media-body">
                    <h4 class="media-heading">{{ comment.author.first_and_last_name }}
                        <small>{{ comment.published|datetimeformat }}</small>
                        {% if comment.allow_edit(current_user) %}
                        <div class="pull-right delete_button">
                        <a href="{{ url_for('material.comment_delete', id=comment.id) }}">
                        <button type="button" class="btn btn-default destroy"">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                        </a>
                        </div>
                        {% endif %}
                    </h4>
                    <div class="{{ 'comment-body' if comment.allow_edit(current_user) else 'not-allow-edit-comment'}}" id="comment_{{comment.id}}">{{ comment.message }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $( document ).ready(function() {
            $('.comment-body').editable('/material/comments/edit/', {
                type: 'textarea',
                cancel: 'Отмена',
                submit: 'ОК',
                tooltip: 'Нажмите для редактирования',
                rows: 3,
                maxlength: 250
            });
        });
    </script>
{% endblock %}