src/app/practice/models.py
from datetime import datetime
import json
from sqlalchemy.schema import UniqueConstraint
from app import db
from app.models import BaseModelMixin
from .enums import TaskTypeEnum, WorkStatus


class Practice(BaseModelMixin, db.Model):
    title = db.Column(db.String(250), nullable=False, default='')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', foreign_keys=user_id)
    tasks = db.relationship('Task', backref='practice', lazy='dynamic', cascade='all, delete-orphan')

    def __repr__(self):
        return self.title


class Task(BaseModelMixin, db.Model):
    practice_id = db.Column(db.Integer, db.ForeignKey('practice.id'), nullable=False)
    question = db.Column(db.String(400), nullable=False, default='')
    type = db.Column(db.Integer, nullable=False, default=TaskTypeEnum.RAW_VALUE.value)
    values = db.Column(db.String, server_default='', nullable=False)  # все ответы
    answer = db.Column(db.String, server_default='', nullable=False)  # правильные


class Homework(BaseModelMixin, db.Model):
    practice_id = db.Column(db.Integer, db.ForeignKey('practice.id'))
    practice = db.relationship('Practice', foreign_keys=practice_id)
    max_questions = db.Column(db.Integer)
    finish_date = db.Column(db.DateTime, nullable=False)
    classroom_id = db.Column(db.Integer, db.ForeignKey('classroom.id'))
    classroom = db.relationship('Classroom', foreign_keys=classroom_id)
    results = db.relationship('WorkResult', lazy='dynamic', cascade='all, delete-orphan')

    __table_args__ = (
        UniqueConstraint('practice_id', 'classroom_id', name='_practice_classroom_unique'),
    )

    @property
    def is_active(self):
        return self.finish_date >= datetime.now()


class WorkResult(BaseModelMixin, db.Model):
    homework_id = db.Column(db.Integer, db.ForeignKey('homework.id'))
    homework = db.relationship('Homework', foreign_keys=homework_id)
    total = db.Column(db.Integer, default=0)
    correct = db.Column(db.Integer, default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', foreign_keys=user_id)
    status = db.Column(db.Integer, nullable=False, server_default=str(WorkStatus.STARTED))
    task_results = db.relationship('TaskResult', lazy='dynamic', cascade='all, delete-orphan')

    __table_args__ = (
        UniqueConstraint('homework_id', 'user_id', name='_homework_user_unique'),
    )

    def generate_data(self):
        data = {}
        for result in self.task_results:
            task_id = result.task_id
            value = result.user_input
            if result.task_type == TaskTypeEnum.RAW_VALUE.value:
                data['answer_{}'.format(result.task_id)] = value
            else:
                values = json.loads(value)
                for val in values:
                    data['answer_{}_{}'.format(task_id, val)] = True
        return data


class TaskResult(BaseModelMixin, db.Model):
    work_result_id = db.Column(db.Integer, db.ForeignKey('work_result.id'), nullable=False)
    work_result = db.relationship('WorkResult', foreign_keys=work_result_id)
    user_input = db.Column(db.String, default='')
    task_id = db.Column(db.Integer, nullable=False)
    task_type = db.Column(db.Integer, nullable=False)

src/app/practice/forms.py
import json
from hashlib import md5
from flask_wtf import FlaskForm

from wtforms import (
    StringField, SelectField, TextAreaField, SubmitField, DateTimeField, BooleanField)
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import DataRequired, Length
from flask_user import current_user

from app.classroom.models import Classroom

from .enums import TaskTypeEnum
from .models import Practice


class PracticeCreateForm(FlaskForm):
    title = StringField('Название', validators=[DataRequired(), Length(max=250)])
    submit = SubmitField('Сохранить')


class TaskCreateForm(FlaskForm):
    question = TextAreaField('Вопрос', validators=[DataRequired(), Length(max=400)])
    type = SelectField('Тип', coerce=int, choices=TaskTypeEnum.choices(), validators=[DataRequired()])
    values = StringField('Ответы')
    answer = StringField('Правильный ответ', validators=[DataRequired()])
    newAnswer = StringField()
    submit = SubmitField('Сохранить')

    def validate(self):
        result = super().validate()
        if not result:
            return result
        if self.type.data == TaskTypeEnum.SINGLE_VALUE.value:
            values = json.loads(self.values.data)
            if len(values) < 2:
                self.newAnswer.errors.append('Должен быть выбор')
                return False
            answer = json.loads(self.answer.data)
            if not answer:
                self.newAnswer.errors.append('Должен быть правильный ответ')
                return False
        return True


def _practice_query():
    return Practice.query.filter_by(user_id=current_user.id)


class HomeworkAddForm(FlaskForm):
    finish_date = DateTimeField('Крайний срок', format='%d.%m.%Y %H:%M', 
        validators=[DataRequired()])
    practice = QuerySelectField('Задание', allow_blank=False, get_pk=lambda x: x.id,
        query_factory=_practice_query)
    classrooms = QuerySelectMultipleField('Группы', allow_blank=False, 
        query_factory=lambda: Classroom.query.all())
    submit = SubmitField('Добавить')


def get_dynamic_form(tasks, salt):
    class BaseForm(FlaskForm):
        pass

    questions = {}
    fields = []
    for task in tasks:
        order = int(md5('{}{}'.format(task.id, salt).encode('utf8')).hexdigest()[:3], 16)
        if task.type == TaskTypeEnum.RAW_VALUE.value:
            id = 'answer_{}'.format(task.id)
            questions[id] = task.question
            fields.append((order, (id, StringField, 'Ответ')))
        else:
            boxes = json.loads(task.values)
            local_fields = []
            for i, box in enumerate(boxes):
                label = box['value']
                id = 'answer_{}_{}'.format(task.id, box['id'])
                if i == 0:
                    questions[id] = task.question
                local_fields.append((id, BooleanField, label))
            fields.append((order, local_fields))

    for i, f in sorted(fields, key=lambda x: x[0]):
        if isinstance(f, list):
            for name, field_cls, label in f:
                setattr(BaseForm, name, field_cls(label))
        else:
            setattr(BaseForm, f[0], f[1](f[2]))

    BaseForm.submit = SubmitField('Сохранить')

    return BaseForm, questions

src/app/practice/views.py
from collections import defaultdict
import json
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_user import current_user, roles_accepted
from sqlalchemy.orm import aliased
from sqlalchemy import and_
from .models import Practice, Task, Homework, WorkResult, TaskResult
from .forms import PracticeCreateForm, TaskCreateForm, HomeworkAddForm, get_dynamic_form
from .tasks import homework_notify
from .enums import TaskTypeEnum
from app import db
from app.auth.enums import Role
from app.auth.decorators import cake
from app.auth.models import User
from app.utils import get_one_or_create

mod_practice = Blueprint('practice', __name__, url_prefix='/practice',
                         template_folder='templates')


@mod_practice.route('/', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def list_view():

    practices = Practice.query.filter_by(user_id=current_user.id)

    return render_template('practice/list.html', practices=practices)


@mod_practice.route('/add', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def create_view():
    form = PracticeCreateForm()
    if form.validate_on_submit():
        practice = Practice(title=form.title.data, user_id=current_user.id)
        db.session.add(practice)
        db.session.commit()
        return redirect(url_for('practice.edit_view', id=practice.id))
    return render_template('practice/create.html', form=form)


@mod_practice.route('/edit/<int:id>', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def edit_view(id):
    practice = Practice.query.get_or_404(id)
    form = PracticeCreateForm(obj=practice)
    if form.validate_on_submit():
        practice.title = form.title.data
        db.session.commit()
        return redirect(url_for('practice.edit_view', id=practice.id))
    return render_template('practice/create.html', form=form, practice=practice)

@mod_practice.route('/delete/<int:id>', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def delete_view(id):
    practice = Practice.query.get_or_404(id)
    if practice.user_id == current_user.id:
        db.session.delete(practice)
        db.session.commit()
    return redirect(url_for('practice.list_view', id=id))


@mod_practice.route('/<int:practice_id>/add_task', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def add_task(practice_id):
    form = TaskCreateForm()
    practice = Practice.query.get_or_404(practice_id)
    if form.validate_on_submit():
        task = Task(question=form.question.data,
                    type=form.type.data,
                    values=form.values.data,
                    answer=form.answer.data,
                    practice_id=practice_id)
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('practice.edit_view', id=practice_id))
    return render_template('practice/task_create.html', form=form, practice=practice)


@mod_practice.route('/edit_task/<int:id>', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def edit_task(id):
    task = Task.query.get_or_404(id)
    form = TaskCreateForm(obj=task)
    if form.validate_on_submit():
        task.question = form.question.data
        task.type = form.type.data
        task.values = form.values.data
        task.answer = form.answer.data
        db.session.commit()
        return redirect(url_for('practice.edit_view', id=task.practice_id))
    return render_template('practice/task_create.html', form=form, practice=task.practice)


@mod_practice.route('/delete_task/<int:id>', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def delete_task(id):
    task = Task.query.get_or_404(id)
    if task.practice.user_id == current_user.id:
        db.session.delete(task)
        db.session.commit()
    return redirect(url_for('practice.list_view'))


@mod_practice.route('/homework/', methods=['GET'])
@cake(Role.TEACHER, Role.STUDENT)
def homework_list_view():
    query = Homework.query.join(Homework.practice).order_by(Homework.finish_date.desc())
    if current_user.role == Role.TEACHER:
        query = query.filter_by(user_id=current_user.id).add_entity(Practice)
    else:
        result_table = aliased(WorkResult)
        query = query.filter(Homework.classroom_id==current_user.classroom_id).join(User).outerjoin(
            result_table, and_(result_table.homework_id==Homework.id, result_table.user_id==current_user.id)
        ).add_entity(result_table).add_entity(Practice).add_entity(User)
    return render_template('practice/homework_list.html', query=query)


@mod_practice.route('/homework/add/', methods=['GET', 'POST'])
@cake(Role.TEACHER)
def homework_add_view():
    form = HomeworkAddForm()
    if form.validate_on_submit():
        homeworks = []
        for classroom in form.classrooms.data:
            homework, created = get_one_or_create(
                db.session, 
                Homework,
                practice_id=form.practice.data.id,
                classroom_id=classroom.id,
                defaults={
                    'finish_date': form.finish_date.data
                }
            )
            if not created:
                homework.finish_date = form.finish_date.data
            db.session.add(homework)
            if created:
                homeworks.append(homework)

        db.session.commit()

        if homeworks:

            homeworks = [h.id for h in homeworks]

            homework_notify.delay(homeworks)
            flash('Оповещения о домашней работе были отправлены на почту!', 'success')
        else:
            flash('Контрольная работа уже добавлена', 'error')
        return redirect(url_for('practice.homework_list_view'))
    return render_template('practice/homework_add.html', form=form)


@mod_practice.route('/homework/delete/<int:id>')
@cake(Role.TEACHER)
def homework_delete_view(id):
    homework = Homework.query.get_or_404(id)
    practice = homework.practice
    if practice.user_id == current_user.id:
        db.session.delete(homework)
        db.session.commit()
    return redirect(url_for('practice.homework_list_view'))


def _work_form(homework):
    practice_id = homework.practice_id
    tasks = Task.query.filter_by(practice_id=practice_id)
    return form_cls(), questions

@mod_practice.route('/homework/solve/<int:id>', methods=['GET'])
@cake(Role.STUDENT)
def homework_solve(id):
    work_result = WorkResult.query.filter_by(homework_id=id, user_id=current_user.id).first()
    if work_result and not work_result.homework.is_active:
        return redirect(url_for('practice.homework_list_view'))
    homework = Homework.query.get_or_404(id)
    practice_id = homework.practice_id
    tasks = Task.query.filter_by(practice_id=practice_id)
    form_cls, questions = get_dynamic_form(tasks, current_user.id)
    data = work_result.generate_data() if work_result else {}
    return render_template('practice/homework_solve.html', form=form_cls(data=data), homework=homework, 
        questions=questions)


@mod_practice.route('/homework/answer/<int:id>', methods=['POST'])
@cake(Role.STUDENT)
def homework_answer(id):
    homework = Homework.query.get_or_404(id)
    practice_id = homework.practice_id
    tasks = Task.query.filter_by(practice_id=practice_id)
    form = get_dynamic_form(tasks, current_user.id)[0]()

    work_result, created = get_one_or_create(
        db.session,
        WorkResult,
        homework_id=homework.id,
        user_id=current_user.id
    )

    if not created and not homework.is_active:
        return redirect(url_for('practice.homework_list_view'))

    if not form.validate_on_submit():
        return redirect(url_for('practice.homework_solve', id=id))

    user_answers = defaultdict(set)
    for field in form:
        if field.name in ['csrf_token', 'submit']:
            continue

        ids = field.name.split('_')[1:]
        id = int(ids[0])
        if len(ids) == 1:
            user_answers[id] = field.data
        else:
            value = int(ids[1])
            if field.data:
                user_answers[id].add(value)

    total = 0
    correct = 0
    result_tasks = []
    for task in tasks:
        total += 1
        if task.type == TaskTypeEnum.RAW_VALUE.value:
            right_answer = task.answer
        else:
            right_answer = set(json.loads(task.answer))

        user_answer = user_answers[task.id]

        result_tasks.append(TaskResult(
            work_result_id=work_result.id,
            user_input=json.dumps(list(user_answer)) if isinstance(user_answer, set) else user_answer,
            task_id=task.id,
            task_type=task.type
        ))

        if user_answer == right_answer:
            correct += 1

    work_result.total = total
    work_result.correct = correct

    db.session.add(work_result)
    work_result.task_results.delete()
    work_result.task_results.extend(result_tasks)
    db.session.commit()

    flash('Задание отправлено', 'success')
    return redirect(url_for('practice.homework_list_view'))


@mod_practice.route('/homework/show_result/<int:id>')
@cake(Role.TEACHER)
def show_result(id):
    homework = Homework.query.get_or_404(id)
    query = User.query.filter_by(
        classroom_id=homework.classroom_id
    ).outerjoin(
        WorkResult,
        and_(WorkResult.user_id == User.id, WorkResult.homework_id == homework.id)
    ).add_entity(
        WorkResult
    ).order_by(User.last_name, User.first_name)
    return render_template('practice/result.html', homework=homework,
        query=query)

src/app/templates/practice/create.html
{% extends 'base.html' %}


{% block head %}
    <style type="text/css">
        li:hover .delete_button{
            visibility: visible;
        }
        .delete_button{
            visibility: hidden;
        }
    </style>
{% endblock %}


{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<div class="container">
    <div class="row">
    <div class="col-lg-2"></div>
        <div class="col-lg-8">
<form action="" method="POST" role="form" class="form-inline">
    {{ form.hidden_tag() }}
    {{ render_field(form.title, tabindex=230) }}
    {{ render_submit_field(form.submit, tabindex=280) }}
</form>
{% if practice %}
    {% if practice.tasks %}
        <ul class="list-group">
            {% for task in practice.tasks %}
                <li class="list-group-item">
                    <a href="{{ url_for('practice.edit_task', id=task.id) }}">{{ task.question}}</a>
                    <div class="pull-right delete_button"><a href="{{ url_for('practice.delete_task', id=task.id) }}"><span class="glyphicon glyphicon-remove"></span></a></div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        Вопросов еще нет
    {% endif %}
    <a href="{{ url_for('practice.add_task', practice_id=practice.id) }}" class="btn btn-info btn-md" role="button">
        Добавить вопрос
    </a>
    <div class="pull-right">
        <a href="{{ url_for('practice.delete_view', id=practice.id) }}" class="btn btn-danger btn-md" role="button">
            Удалить
        </a>
    </div>
    {% endif %}
    </div>
        </div>
</div>
{% endblock %}

src/app/templates/practice/homework_add.html
{% extends 'flask_user/member_base.html' %}


{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<form action="" method="POST" role="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.finish_date, tabindex=230) }}
    {{ render_field(form.practice, tabindex=230) }}
    {{ render_field(form.classrooms, tabindex=230, **{'data-placeholder': " "}) }}
    {{ render_submit_field(form.submit, tabindex=280) }}
</form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $( document ).ready(function() {
            $('#finish_date').datetimepicker({
                format:'d.m.Y H:i'
            });
            $('#classrooms').chosen();
        });
    </script>
{% endblock %}

src/app/templates/practice/homework_list.html
{% extends 'base.html' %}


{% block head %}
    <style type="text/css">
        tr:hover td .delete_button{
            visibility: visible;
        }
        .delete_button{
            visibility: hidden;
        }
    </style>
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            {% if query %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Название</th>
                            {% if current_user.role == Role.STUDENT %}
                            <th>Преподаватель</th>
                            {% endif %}
                            <th>Группа</th>
                            <th>Срок выполнения</th>
                            <th>Результат</th>
                            {% if current_user.role == Role.TEACHER %}
                            <th></th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for row in query %}
                        {% if current_user.role == Role.TEACHER %}
                            {% set homework, practice = row %}
                        {% elif current_user.role == Role.STUDENT %}
                            {% set homework, result, practice, user = row %}
                        {% endif %}
                        {% if current_user.role == Role.STUDENT %}
                            {% if homework.is_active %}
                                {% set tr_cls = 'warning' %}
                            {% else %}
                                {% set tr_cls = 'success' if result else 'danger' %}
                            {% endif %}
                        {% elif current_user.role == Role.TEACHER %}
                            {% set tr_cls = 'success' if not homework.is_active else 'info' %}
                        {% endif %}
                        
                        <tr class="{{ tr_cls }}">
                            {% if current_user.role == Role.TEACHER %}
                                {% set url = url_for('practice.edit_view', id=practice.id) %}
                            {% elif current_user.role == Role.STUDENT %}
                                {% set url = url_for('practice.homework_solve', id=homework.id) if homework.is_active else None %}
                            {% endif %}
                            
                            <td>
                                {% if url %}
                                    <a href="{{ url }}">{{ practice.title }}</a>
                                {% else %}
                                    {{ practice.title }}
                                {% endif %}
                            </td>
                            {% if current_user.role == Role.STUDENT %}
                            <th>{{ user.first_and_last_name }}</th>
                            {% endif %}
                            <td>{{ homework.classroom.title }}</td>
                            <td>{{ homework.finish_date|datetimeformat }}</td>
                            {% if current_user.role == Role.TEACHER %}
                            <td><a href="{{ url_for('practice.show_result', id=homework.id) }}">Показать результаты</a></td>
                            <td>
                                <div class="pull-right delete_button">
                                <a href="{{ url_for('practice.homework_delete_view', id=homework.id) }}" class="btn btn-danger btn-md" role="button">Удалить</a>
                                </div>
                            </td>
                            {% else %}
                                {% if result %}
                                    {% set val_res = '{} / {}'.format(result.correct, result.total) if not homework.is_active else 'На проверке' %}
                                {% else %}
                                    {% set val_res = 'Не пройдено' %}
                                {% endif %}
                                <td>{{ val_res }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Ничего не добавлено
            {% endif %}
            {% if current_user.role == Role.TEACHER %}
            <a href="{{ url_for('practice.homework_add_view') }}" class="btn btn-info btn-md" role="button">Добавить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/app/templates/practice/homework_solve.html
{% extends 'base.html' %}


{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<div class="container">
    <div class="row">
    <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h1>{{ homework.practice.title }}</h1>
            <form action="{{ url_for('practice.homework_answer', id=homework.id) }}" method="POST" role="form" class="form-style-disabled">
                {{ form.hidden_tag() }}
                {% for field in form if field.widget.input_type != 'hidden' and field.name != 'submit' %}
                    {% if field.name in questions %}
                        <hr>
                        <h3>{{ questions[field.name] }}</h3>
                    {% endif %}

                    {% if field.type == 'StringField' %}
                        {{ render_field(field) }}
                    {% else %}
                        <div class="form-check">
                            {{ field }}
                            {{ field.label }}
                        </div>
                    {% endif %}
                {% endfor %}
                {{ render_submit_field(form.submit) }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/app/templates/practice/list.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            {% if practices %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Дата создания</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for practice in practices %}
                        <tr>
                            <td><a href="{{ url_for('practice.edit_view', id=practice.id) }}">{{ practice.title }}</a></td>
                            <td>27.05.2017</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Ничего не добавлено
            {% endif %}
            <a href="{{ url_for('practice.create_view') }}" class="btn btn-info btn-md" role="button">Добавить</a>
        </div>
    </div>
</div>
{% endblock %}

src/app/templates/practice/result.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h1>{{ homework.practice.title }}. Группа: {{ homework.classroom.title }}</h1>
            {% if query %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>ФИО</th>
                            <th>Результат</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student, result in query %}
                            {% set tr_cls = 'success' if result %}
                            {% set tr_cls = 'warning' if not result else tr_cls %}
                            {% set tr_cls = 'danger' if not result and homework.finish_date >= current_time else tr_cls %}
                        
                        <tr class="{{ tr_cls }}">
                            <td>{{ student.fio }}</td>
                            {% if result %}
                                <td>{{ result.correct }} / {{ result.total }}</td>
                            {% else %}
                                <td>Не пройдено</td>
                            {% endif%}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Результатов нет
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/app/templates/practice/task_create.html
{% extends 'flask_user/member_base.html' %}


{% block head %}
<link href="{{ url_for('static', filename='css/task.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<a href="{{ url_for('practice.edit_view', id=practice.id) }}">{{ practice.title }}</a>
<form action="" method="POST" role="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.question, tabindex=230) }}
    {{ render_field(form.type, tabindex=230) }}
    {{ render_field(form.answer, tabindex=230) }}
    {{ render_field(form.values, tabindex=230) }}
    <fieldset class="form-group" id="answersSet">
        <legend>Ответы</legend>
        {{ render_field(form.newAnswer, label_visible=False, placeholder="Введите ответ") }}
    </fieldset>
    <div>
    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
</form>

<script type="text/html" id="valueFieldTemplate">
    <div class="form-check surrogat">
        <input type="checkbox" id="optionsRadios<%- id %>" value="<%- id %>" <%- extra %>>
        <input class="edit" value="<%- title %>" id="inputField<%- id %>" style="width:300px;">
        <button type="button" class="btn btn-default destroy" id="destroyBtn<%- id %>">
            <span class="glyphicon glyphicon-remove"></span>
        </button>
    </div>
</script>
{% endblock %}


{% block scripts %}
<script src="{{ url_for('static', filename='js/task.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/js/underscore.js') }}"></script>
{% endblock %}